### ISSUE TITLE
Our services directory is a mess

### ISSUE THREAD

**Issue by benthorner** [alphagov/content-publisher#1256]
As our app grows, an increasing amount of random code is landing in the `app/services` directory. I'm worried it will become impractical to improve on this, as the number of special cases will only increase. Some pain points off the top of my head (definitely not exhaustive):

   - We have a variety of naming styles, which makes it harder to find existing 'services' and to decide on names for new ones
   - We have a variety of interface styles, which makes it harder to understand existing 'services' and decide on interfaces for new ones

Some possible aims (also not exhaustive):

   - We agree what code is a 'service' and what is not
   - We agree on the interface we expect for our services
   - We agree on the naming convention we use for services

Non-aims (but may happen anyway):

   - We categorise the non-services currently in `app/services`
   - We decide on `app/lib` v. `lib/` once and for all
   - We decide if Catrin should give Zane a second chance

## Current Situation

Currently our services directory looks like this:

   - **govspeak_document(.rb)/**
       - 4 relates classes, various methods
   - **requirements/**
      - 15 related classes, various methods
   - **versioning/**
      - 7 related classes/supporting classes, various methods
   - **asset_manager_service.rb**
      - 4 related methods e.g. `delete`
   - **contacts_service.rb**
      - 2 methods: `all_by_organisation`, `by_content_id`
   - **date(time)_parser.rb**
      - 2 methods: `parse`, `issues`
   - **delete_draft_service.rb**
      - 1 method: `delete`
   - **draft_asset_cleanup_service.rb**
      - 1 method: `call`
   - **edition_assertions.rb**
      - 2 methods: `assert_edition_state`, `assert_edition_access`
   - **edition_filter.rb**
      - 2 methods: `editions`, `filter_params`
   - **file_attachment_blob_service.rb**
      - 1 method: `create_blob_revision`
   - **image_blob_service.rb**
      - 1 method: `create_blob_revision`
   - **image_centre_cropper.rb**
      - 1 method: `dimensions`
   - **image_normaliser.rb**
      - 2 methods: `dimensions`, `normalised_file`
   - **linkables_service.rb**
      - 2 methods: `select_options`, `by_content_id`
   - **organisation_service.rb**
      - 2 methods: `by_content_id`, `alternative_format_contact_email`
   - **path_generator_service.rb**
      - 1 method: `path`
   - **preview_asset_service.rb**
      - 3 methods: `upload_assets`, `upload_asset`, `can_preview_asset?`
   - **preview_auth_bypass_service.rb**
      - 2 methods: `auth_bypass_id`, `preview_token`
   - **preview_service.rb**
      - 2 methods: `create_preview`, `try_create_preview`
   - **publish_asset_service.rb**
      - 1 method: `publish_assets`
   - **publish_service.rb**
      - 1 method: `publish`
   - **publishing_api_payload.rb**
      - 2 methods: `payload`, `intent_payload`
   - **remove_service.rb**
      - 1 method: `remove`
   - **schedule_service.rb**
      - 2 methods: `schedule`, `reschedule`
   - **scheduled_publishing_failed_service.rb**
      - 1 method: `call`
   - **topic_index_service.rb**
      - 1 method: `lookup`
   - **unique_filename_service.rb**
      - 1 method: `call`
   - **withdraw_service.rb**
      - 1 method: `call`

## Existing ~~Wheels~~ Approaches

Several apps on GOV.UK have identifiable approaches that are related to the problem we're having:

   - [Content Publisher](https://github.com/alphagov/content-publisher/blob/master/app/interactors/file_attachments/destroy_interactor.rb) uses 'interactors' to handle a lot of controller actions. This could be reused for services, but has the potential downside of making our current use of interactors more complex
   - [Publishing API](https://github.com/alphagov/publishing-api/blob/master/app/commands/base_command.rb) has a (bloated) concept of 'commands'. This is more related to our existing Interactor approach for controller actions, as [this blog illustrates](https://medium.com/devcupboard/command-pattern-a-new-way-to-organize-your-domain-layer-5fe4cb8d3130).
   - [Email Alert API](https://github.com/alphagov/email-alert-api/blob/master/app/services/auth_token_generator_service.rb) has a prevalent '.call' interface for some of its services and a clear naming scheme for all of them. If we adopt a similar approach, we should consider using a base class to reduce duplication.
   - [Content Data Admin](https://github.com/alphagov/content-data-admin/blob/master/app/services/fetch_document_children.rb) also has a '.call' interface for all of its services and some kind of naming scheme; it differs from the Publishing API in the way the args are passed (into 'new' vs. 'call'). It also illustrates [an extension to their own convention](https://github.com/alphagov/content-data-admin/blob/master/app/services/find_content.rb).

## Possible Approach

There are [quite](http://johnnyji.me/rails/2015/05/19/lib-folder-vs-services-in-rails.html) [a lot](https://www.toptal.com/ruby-on-rails/rails-service-objects-tutorial) [of opinions](https://codeclimate.com/blog/what-code-goes-in-the-lib-directory/) out there on how to classify/locate code. In order to generate some discussion, let's pick one and see what the consequences would be.

   - All files in `app/services` should end in `_service.rb`
   - All files in `app/services` should support a `.call` interface
   - All files in `app/services` should inherit from `ApplicationService`
   - Most files in `app/services` do one thing only

The `ApplicationService` is partly to define the `.call` interface consistently and without duplication; and partly to act as a 'marker' that something is a 'service'. 

The following shows how this would affect the existing files. Any files that can't/won't meet these conventions will need to go somewhere else (e.g. `app/lib`).

### Natural Services

   - scheduled_publishing_failed_service.rb
   - topic_index_service.rb
   - unique_filename_service.rb
   - withdraw_service.rb
   - remove_service.rb
   - publish_service.rb
   - publish_asset_service.rb
   - file_attachment_blob_service.rb
   - image_blob_service.rb
   - path_generator_service.rb
   - delete_draft_service.rb
   - draft_asset_cleanup_service.rb

### Non-Services

   - **govspeak_document(.rb)/**
       - 4 relates classes, various methods
   - **requirements/**
      - 15 related classes, various methods
   - **versioning/**
      - 7 related classes/supporting classes, various methods
   - **edition_assertions.rb**
      - 2 methods: `assert_edition_state`, `assert_edition_access`
   - **date(time)_parser.rb**
      - 2 methods: `parse`, `issues`

### Potential Services

   - **publishing_api_payload.rb** ✅
      - 2 methods: `payload`, `intent_payload`
      - suggestion: 1 service/support class for each method
      - suggestion: nest by service e.g. ScheduleService::IntentPayload
   -  **preview_auth_bypass_service.rb**  ❌
      - 2 methods: `auth_bypass_id`, `preview_token`
      - suggestion: rename to `preview_auth_bypass.rb`
   - **schedule_service.rb** ✅
      - 2 methods: `schedule`, `reschedule`
      - suggestion: combine methods or split service
   - **preview_service.rb** ✅
      - 2 methods: `create_preview`, `try_create_preview`
      - suggestion: make `try_create_preview` the default method
      - suggestion: emulate `create_preview` with a flag
   - **preview_asset_service.rb** ✅
      - 3 methods: `upload_assets`, `upload_asset`, `can_preview_asset?`
      - suggestion: make `upload_asset` the default method
      - suggestion: move `can_preview_asset?` to the Asset model
      - suggestion: move `upload_assets` to the PreviewService
   - **edition_filter.rb** ✅
      - 2 methods: `editions`, `filter_params`
      - suggestion: move `filter_params` to controller/interactor
      - suggestion: rename to `edition_filter_service.rb`
   - **organisation_service.rb** ❌
      - 2 methods: `by_content_id`, `alternative_format_contact_email`
      - suggestion: not a service; more like a helper/adapter; probably not a model
   - **contacts_service.rb** ❌
      - 2 methods: `all_by_organisation`, `by_content_id`
      - suggestion: not a service; more like a helper/adapter; probably not a model
   - **asset_manager_service.rb** ❌
      - 4 related methods e.g. `delete`
      - suggestion: not a service; more like a helper/adapter; probably not a model
   - **linkables_service.rb** ❌
      - 2 methods: `select_options`, `by_content_id`
      - suggestion: not a service; more like a helper/adapter; probably not a model
   - **image_centre_cropper.rb** ✅
      - 1 method: `dimensions`
      - suggestion: possible nested support class for ImageBlobService
   - **image_normaliser.rb** ✅
      - 2 methods: `dimensions`, `normalised_file`
      - suggestion: possible nested support class for ImageBlobService

Now it's open to the floor: how does the above approach look to you? What other approach(es) could we do (preferably in the short term)?

**Comment by kevindew** [comment]
This is looking really interesting Ben - looking forward to chatting more about it at the meeting this afternoon. 

The big question we seem to have though is who is Catrin and Zane, and does he really deserve a second chance?

**Comment by kevindew** [comment]
Thanks again Ben for putting this together. It'd be really nice to resolve this in the app.

I'm keen on:

- only storing things we deem "services" in the services directory;
- services have a consistent interface.

I'm also happy with ApplicationService but have some concerns. It does seem nice to have a single inheritance point to avoid boilerplate and it is consistent, but it does feel like a surprising class to have in a Rails app.

Just to check the suggestion is that these services have a single `.call` interface consistent with interactors? 

Any thoughts/ideas about consistency in output if any?

One thing I wonder though is if we give these services a consistent interface wouldn't it make sense for them to be consistent with interactors. That'd give us an existing pattern to use? As far as I'm aware the argument against that is mostly about code location rather than class structure, though I know that is not trivial to solve.

Also, if any of these services need supporting classes (which you've alluded to with ScheduleService::IntentPayload) would these be within folders within "services",  "services/schedule_service/intent_payload.rb"? that's something I'd be happy with but I'm checking. 

Finally another thing I wondered about was whether trying to make our service more verb based in naming to describe what they do, which is a common approach for services, e.g: SchedulerService or PreviewCreaterService. I feel like that could help make their single responsibility clearer.

---

Then on the other side of the coin we have where to put things that aren't services.

Do we have any other contenders between `lib/` and `app/lib`? (hopefully not)

and what we'd intend to do is move code into there so it may look like:

<img width="350" alt="Screen Shot 2019-07-23 at 18 13 03" src="https://user-images.githubusercontent.com/282717/61732568-c8041380-ad75-11e9-80ca-dbbdaa9e4231.png">

is that correct?

I know other apps have used their name as a lib namespace, for example [whitehall](https://github.com/alphagov/whitehall/tree/master/lib/whitehall) but I assume we're not going to consider that.

**Comment by benthorner** [comment]
@kevindew thanks for the comments. I'm glad we're in agreement on the main changes but it'll be interesting to see how others interpret them. Just to summarise your questions/concerns:

   - The `ApplicationService` class might be surprising
   - The `.call` interface is suggestive of Interactors
   - Supporting classes could go into sub folders?
   - Services might be more specifically named?

In answer to the two questions: yes, and yes, although for the latter I was trying to avoid changing too much, so the end result is still recognisable to what we have now. I'm not fussed.

The interface is a bit more tricky. I'm approaching this differently to Interactors: we already have a bunch of 'service' classes to guide us, whereas we had no Interactors previously. Although the Interactor pattern would work for services, even such a small thing seems overkill:

   - The context aspect would be unused without rewriting our services
   - The adherence to Interactors limits the future flexibility of services

In the last point, I'm referring to the [breakaway service I found in Content Data](https://github.com/alphagov/content-data-admin/blob/master/app/services/find_content.rb). Although this is probably not a good example, my preference right now is to just make the minimum set of changes to achieve some superficial (directory) consistency.

Do you think we should go further?

**Comment by kevindew** [comment]
> The interface is a bit more tricky. I'm approaching this differently to Interactors: we already have a bunch of 'service' classes to guide us, whereas we had no Interactors previously. Although the Interactor pattern would work for services, even such a small thing seems overkill:
> 
> * The context aspect would be unused without rewriting our services
> * The adherence to Interactors limits the future flexibility of services
> 
> In the last point, I'm referring to the [breakaway service I found in Content Data](https://github.com/alphagov/content-data-admin/blob/master/app/services/find_content.rb). Although this is probably not a good example, my preference right now is to just make the minimum set of changes to achieve some superficial (directory) consistency.
> 
> Do you think we should go further?

I'm not too concerned about the breakaway service example you've got as I think that should be discouraged. Once you have a single call interface that creates an instance of the object it get's rather weird to have another class create an instance of it - generally leading to unnecessary arguments.

What Interactors do well is allow us to handle abort cases and provide a pretty consistent interface for the data that is returned. What they do rather badly is allow you to know what inputs go in. 

I did hope to go through our services this afternoon to do some assessing about whether they'd benefit or not from this, however time ran away from me. From memory I don't think we have services that have abort cases as we expect callers of a service to be in a correct state (otherwise unhandled exceptions), whereas I'm not so sure on return patterns - though I'd guess mostly services mutate their input rather than return a thing. It's also probably not too big a deal if services return an object or a hash.

Off top of my head I'd be inclined to agree that the pattern may not make full sense for services, and that in itself defines characteristics of services. That does potentially leave a little hole for anything that has to orchestrate a number of services and deal with state, but that doesn't seem to be something that is causing us a problem today.

**Comment by kevindew** [comment]
Some more thoughts I've had that I'm jotting down in advance of the meeting.

## What makes a service

I had a bit of a ponder and look at our code to see what patterns seem to make a service and what is more ambiguous.

The most common, and likely most natural, properties I've identified that make a service are:

- Take an object and perform a business operations on it
- Used to perform state transitions and side effects
- Generally used as a means to perform a state transition
- May not have an output
- Normally tested by monitoring side effects rather than output

Example: PublishService

The other area of things that @benthorner has identified as some of the natural service are things that seem to meet the behaviour of [Pure Function as an Object](https://www.tomdalling.com/blog/ruby/pure-function-as-an-object-PFAAO-pattern/). Some examples of these are UniqueFilenameService, ImageCentreCropper. These are things that may be too complex for a single function and thus are represented as a class.

These seem to differ in characteristics to the previous service definition in that these:

- Tend to not have side effects
- Tested based on output
- Used to generate an output to put into another function
- Could feasibly be considered as a global function

Between this PFAAO and the side-effect service definition there's also creational services like FileAttachmentBlobService and ImageBlobService which are employing a factory pattern than a service. These seem to be in between the definitions as they have side effects and the output is used. 
 
The thing I found that seems to meet no consistency is the EditionFilter - but I'm out of time to write anything on that now.

## Whether to store code in `app/lib` or `lib`

This seems to be a great unresolved question in the Rails world - which has become [more complex](https://github.com/rails/rails/issues/13142#issuecomment-275549669) in recent times. This doc here as some info: https://medium.com/extreme-programming/what-goes-in-rails-lib-92c74dfd955e on purposes of directories. My conclusion from all reading though is that there are lots of contradictions to all logic and it's essentially just a point of confusion in the Rails world, any assertions that lib doesn't contain domain logic seem flawed as it seems almost inevitable that an app will end up with a rake task with domain logic and they cannot live anywhere other than lib.

So I tried to jot up a quick list of the pros and cons of switching to `app/lib` over putting code in `lib` - where you can pretty much flip them to get the over way.

Pros:

- Everything is within `app` directory - you don't have to make a mental leap to a different folder
- The `app/lib` has no existing baggage like tasks or generators
- Needs no changes to autoloading (`lib` requires [a change](https://github.com/alphagov/content-publisher/commit/da1efa353bd8640c3a52b66eb8fa3589fdbaabef#diff-b1fe55db50c712fef0673345e5b9c0d9R36))

Cons:

- 2 `lib` directories - hard to define what belongs in each, easier to end up checking the wrong one (problem I have on any GOV.UK apps that use app/lib)
- naming collision for spec placement. For example specs for `app/lib` and `lib` would both logically belong in `spec/lib`

My assessment on comparing these is that I prefer putting code in `lib` and autoloading it. We don't seem to have the problem listed in https://github.com/rails/rails/issues/13142#issuecomment-29788440 where we have lots of junk in lib already.

**Comment by kevindew** [comment]
Thank you to the attendees of the meeting yesterday to discuss this issue further. I'm going to try summarise the decisions made and the follow up actions.

We agreed:

- `app/services` is a mess and has too little consistency between classes or naming;
- `lib` is the appropriate directory for code that does not have a logical home in one of the `app/*` directories;
- services (classes in `app/services`) should have the same public interface: a `Service.call` method;
- services will inherit from `ApplicationService` similar to other `app/*` directories, this will provide a consistent interface;
- services will have class names that are suffixed with Service, for example PublishService;
- services can have supporting classes in nested directories, for example `app/services/publish_service/payload.rb`.

We discussed what constitutes a service class. We didn't come to a concrete conclusion as to the boundaries of what is a service or not, however we did identify aspects. We felt that a service class should allow performing a single operation and it's name should describe what it does - for example EditionPublisherService is good, whereas AssetManagerService is bad due to purpose ambiguity. We felt the most natural services were classes, such as ScheduleService, that cause side effects such as performing a state transition or updating an API and are tested based on the side effects. We were less sure about two other kinds of classes identified: creational ones, such as ImageBlobService, that produce an output and side effects; and helper ones, such as UniqueFilenameService, that have no side effects and act as a [pure-function-as-an-object](https://www.tomdalling.com/blog/ruby/pure-function-as-an-object-PFAAO-pattern/).


We went through the classes/directories within app/services to decide their fates

- contacts_service.rb - move to lib, rename as Contacts (pending wider decision on adapter/repository classes)
- date_parser.rb - move to lib
- datetime_parser.rb - move to lib
- delete_draft_service.rb - service
- draft_asset_cleanup_service.rb, service
- edition_assertions.rb - move to lib
- edition_filter.rb - move to lib
- file_attachment_blob_service.rb - to be decided whether service or not (creational)
- govspeak_document/ - move to lib
- govspeak_document.rb - move to lib
- image_blob_service.rb - to be decided whether service or not (creational)
- image_centre_cropper.rb - not service, unclear of destination
- image_normaliser.rb - not service, unclear of destination
- linkables_service.rb - move to lib, rename as Linkables (pending wider decision on adapter/repository classes)
- organisation_service.rb - move to lib, rename as Organisation (pending wider decision on adapter/repository classes)
- path_generator_service.rb - service
- preview_asset_service/ - service supporting classes
- preview_asset_service.rb - service
- preview_auth_bypass_service.rb - not service, rename to PreviewAuthBypass
- preview_service.rb - service
- publish_asset_service.rb - service
- publish_service.rb - service
- publishing_api_payload.rb - not service, may be part of a service supporting class
- remove_service.rb - service
- requirements/ - move to lib
- schedule_service.rb - service
- scheduled_publishing_failed_service.rb - service
- topic_index_service.rb - move to lib, rename as TopicIndex (pending wider decision on adapter/repository classes)
- unique_filename_service.rb - service
- versioning/ - move to lib
- withdraw_service.rb - service

For the services that are identified to remain as services we intend to look into refactoring them to meet the shared interface and we intend to consider their naming to better capture their purpose.

Follow up actions:

- start moving code to `lib`
- rename and move classes that are currently named as `*Service` but will be moving to `lib`;
- create `ApplicationService` and refactor compatible services to use it;
- review naming of services;
- refactor/rethink services that are not compatible with ApplicationService;
- reflect on changes made;
- produce an ADR documenting the decision.

**Comment by benthorner** [comment]
@kevindew just thought of one small decision we didn't cover: should we permit any kind of `.call` interface, or enforce hash arguments consistently? I mention it because it's another one of those repetitive and ultimately low value decisions that get made for each class individually :-).

**Comment by kevindew** [comment]
> @kevindew just thought of one small decision we didn't cover: should we permit any kind of `.call` interface, or enforce hash arguments consistently? I mention it because it's another one of those repetitive and ultimately low value decisions that get made for each class individually :-).

I'd suggest starting with any kind and see if that gets us into bother. It seems verbose to require a hash given some things may have a single argument and the class name already describes what it's dealing with - for example `EditionDeleter.call(edition: edition)`. However keyword arguments become required for understanding if we're either dealing with bools or have a number of parameters.

Only thing I'm not sure is if:

```
  def self.call(*args)
    new(*args).call
  end
```

has any effects on what args are allowed - but I think it's cool, it'd just be blocks that don't get passed by default?

**Comment by benthorner** [comment]
We've now done the bulk of the work we planned to address this issue, such that all top-level classes in `app/services/` now inherit from a common `ApplicationService` interface. In future work, we would like to:

   - Review the naming of the classes in `app/services/`. For example, we could consider if `PreviewService` could be accurately named as e.g. `CreatePreviewService` or similar
   - Review the approach to passing arguments to services - as a list or using keyword args - now that we group them all together in a single method `.call`

Finally, we would like to write an ADR to document our approach to services, describing what we mean by a 'service' at a high-level and in code, as well as documenting the changes we made, as [described in related PRs](https://trello.com/c/6WhtlGQB/1115-finish-work-separating-services-and-non-services-from-services).

**Comment by benthorner** [comment]
Closing as we believe this is paid down. @kevindew has proposed to document how we do services as part of our conventions, here: https://trello.com/c/lfZuWBlH/1513-record-our-technical-conventions-eg-naming-conventions.
