### ISSUE TITLE
Strategy for Feature Tests

### ISSUE THREAD

**Issue by benthorner** [alphagov/content-publisher#79]
After looking through our feature tests, I've got a few questions that I think would be good to for us to discuss. Hopefully this will turn into a common approach we can use.

   1) How much of our config do we test? We don't currently test all our config every time we run the tests. It seems like we should be testing all of our config before we deploy the app.

   2) How many tests should we have? We probably don't want to go full Whitehall and have 'feature x format' many tests - takes way too long - but we need to test every feature somehow.

   3) Where should we put our tests? Currently we've got a folder called 'integration', but we could also have 'features' and 'integration' to separate UI and backend-y integration tests.

   4) Should we have loops in our tests? Personally I find lots of nesting hard to read, and as the formats become more complex and varied, I can't see how we'll maintain simple loop bodies.

One particular example that troubles me is validations. With all the different validations across different formats, is there a simple approach to test they all work and are configured properly?

**Comment by davbo** [comment]
Agreed with @tijmenb, great questions. I'll need to think on it a while longer to come up with clearer answers but here are my initial thoughts.

1) I do think we should aim for high test coverage on our code. I'd like to consider the config separately to that. That might mean supplying test format configuration in order to maximise coverage, but I'm not certain that's required in feature tests. I tend to think of them as lower coverage but complete journeys.

2) Hopefully we could have few feature tests for end-to-end journey and more unit tests which supply test configuration for catching happy/sad path and edge cases (e.g. what if I make the required body length massive, really small, negative etc).

3) 'integration' -> 'features' 👍 

4) I'm more familiar with these types of test expressed as "paramaterized tests" which I have mixed feelings about. Structuring as paramaterised tests does benefit from removing iteration and make test data more prominent. Looks like it's possible with https://github.com/tomykaira/rspec-parameterized but not sure if that's any good or a ruby way of doing things.

As I said I need to think on it a bit more but that's my intial reaction to the questions.

**Comment by kevindew** [comment]
Great discussion all 👍 

>How much of our config do we test? We don't currently test all our config every time we run the tests. It seems like we should be testing all of our config before we deploy the app.

I've pondered this a bit and don't have a particularly strong answer. Our config is basically the backbone of the app and enables everything, but testing config feels totally wrong. 

I think at a high level it's good to know that every config produces something that is usable, which seems quite consistent with @tijmenb's config feature tests point.

I'd suggest anything that's outside of the top level of yaml (e.g. validations etc) are things that shouldn't be tested per format.

> How many tests should we have? We probably don't want to go full Whitehall and have 'feature x format' many tests - takes way too long - but we need to test every feature somehow.

I've always enjoyed the notes @heathd wrote about cucumber testing for Whitehall (which sadly were recently deleted): https://github.com/alphagov/whitehall/blob/099f53e35cdd0ea63a2349be3766c98e65521ce3/docs/testing.md#cucumber as an approach to feature testing and find it to be useful guidance.

I'd agree we don't want to do format x feature, just every feature.

I think the approach now is cool that we pull out a document with that feature. I'm not sure it will scale depending on how much docs vary but that does seem a neat way to have that now without getting too bogged in testing hypotheticals.

> Where should we put our tests? Currently we've got a folder called 'integration', but we could also have 'features' and 'integration' to separate UI and backend-y integration tests.

Yeah I think putting the tests in a features directory would be more idiomatic.

> Should we have loops in our tests? Personally I find lots of nesting hard to read, and as the formats become more complex and varied, I can't see how we'll maintain simple loop bodies.

In general I'd agree to that loops should be avoided in tests since it can easily end up with confusing tests with logic to set up.

I don't think they should be forbidden though and when I consider the alternatives I think https://github.com/alphagov/content-publisher/blob/master/spec/integration/create_a_document_spec.rb is currently preferable to having individual tests for each format. I do expect that'll change as formats evolve and diverge but feels like a future problem.

> One particular example that troubles me is validations. With all the different validations across different formats, is there a simple approach to test they all work and are configured properly?

I'd be expecting that you only want to test you can get a validation error message at feature level (even that is a bit off the happy path) and that you'd want to be unit or integration testing that validations work.

Re: randomness in tests - where we do embrace it, it'd be great to have it explicit in the fail and how to replicate when it's pertinent. No ❤️for flaky tests.

**Comment by benthorner** [comment]
Thanks to everyone for all their thoughts on this. I'm going to try and summarise the areas where I think we agree. Feel free to comment on my comments ;-).

   - Easy one: we should move all the feature tests into a features directory (vs. integration)
   - Use loops to ensure 'core workflow' is tested (current: create/edit, future: +associations)
   - Test every feature, using explicit, logged randomness to avoid format-specific behaviour
   - Test edge cases (e.g. validations, exceptions) lower down, but still feature test error UI
   - Test more nested parts of the config (e.g. payload generation, validations) lower down

Interestingly, the randomness approach we've adopted to select a document_type would make it easier to change to a test-format model if we ever decided to.

**Comment by benthorner** [comment]
The tests have changed a lot since I wrote this issue, to the point where I no longer have any questions about our approach. We've departed from trying to test formats+features at the same time, as doing this for associations was becoming too complex; instead, we test features and formats (i.e. creating a maximal payload) separately.
